
services:
  php:
    image: php85-cicd-image:1.0
    container_name: cicd-one
    volumes:
      - ./:/var/www/html
    networks:
      devnet:
        aliases:
          - php-cicd-one

  nginx:
    image: myorg/nginx:latest
    container_name: nginx-for-cicd-one
    environment:
      SERVER_NAME: localhost
      DOCUMENT_ROOT: /var/www/html/public # public for laravel project
      PHP_UPSTREAM: php-cicd-one   # service name = DNS name on devnet, # unique alias
    volumes:
      - ./:/var/www/html
    ports:
      - "8085:80"
    depends_on:
      - php
    networks: [devnet]

networks:
  devnet:
    external: true
    driver: bridge
