name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code and refresh app
        run: |
          cd /home/sohel/tipu/projects/cicd_one
          git pull origin main
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
